In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('/content/loan_sanction_test.csv')

In [3]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural

In [4]:
data.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [9]:
data.select_dtypes(include=np.number).fillna(0).max()

ApplicantIncome      72529.0
CoapplicantIncome    24000.0
LoanAmount             550.0
Loan_Amount_Term       480.0
Credit_History           1.0
dtype: float64

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             356 non-null    object
 2   Married            367 non-null    object
 3   Dependents         357 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      344 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

In [15]:
data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Property_Area']=le.fit_transform(data['Property_Area'])
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,2
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,2
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,2
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,2
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,2
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,2
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,1
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,0
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,0

In [26]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
data['ApplicantIncome']=ss.fit_transform(data[['ApplicantIncome']])
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,0.186461,0,110.0,360.0,1.0,2
1,LP001022,Male,Yes,1,Graduate,No,-0.352692,1500,126.0,360.0,1.0,2
2,LP001031,Male,Yes,2,Graduate,No,0.039641,1800,208.0,360.0,1.0,2
3,LP001035,Male,Yes,2,Graduate,No,-0.502774,2546,100.0,360.0,NaN,2
4,LP001051,Male,No,0,Not Graduate,No,-0.311909,0,78.0,360.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,-0.162439,1777,113.0,360.0,1.0,2
363,LP002975,Male,Yes,0,Graduate,No,-0.132056,709,115.0,360.0,1.0,2
364,LP002980,Male,No,0,Graduate,No,-0.317211,1993,126.0,360.0,NaN,1
365,LP002986,Male,Yes,0,Graduate,No,0.039641,2393,158.0,360.0,1.0,0
366,LP002989,Male,No,0,Graduate,Yes,0.896087,0,98.0,180.0,1.0,0

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

x = data.drop(['LoanAmount','Loan_Amount_Term','Property_Area'], axis=1)
y = data['Property_Area']


x = x.drop('Loan_ID', axis=1)

x['Dependents'] = x['Dependents'].replace('3+', '3').astype(float)
x['Dependents'] = x['Dependents'].fillna(x['Dependents'].mode()[0])


categorical_cols = x.select_dtypes(include='object').columns
x = pd.get_dummies(x, columns=categorical_cols, drop_first=True)

numerical_cols_with_nans = x.select_dtypes(include=np.number).isnull().sum()
numerical_cols_with_nans = numerical_cols_with_nans[numerical_cols_with_nans > 0].index
for col in numerical_cols_with_nans:
    x[col] = x[col].fillna(x[col].mode()[0])


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


model = RandomForestClassifier(random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [35]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.32432432432432434

In [37]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

data = {
"Hours":[1,2,3,4,5],
"Marks":[35,45,55,65,80],
"Pass":[0,0,1,1,1]
}

df = pd.DataFrame(data)

X = df[["Hours","Marks"]]
y = df["Pass"]

model = RandomForestClassifier(n_estimators=10)

model.fit(X,y)

prediction = model.predict([[3,60]])

print("Prediction:",prediction)

y_pred = model.predict(X)

print("Accuracy:",accuracy_score(y,y_pred))

Prediction: [1]
Accuracy: 1.0

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(