In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/healthcare_dataset.csv.zip')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [ ]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [ ]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [ ]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [ ]:
df.shape

(55500, 15)

In [ ]:
df['Test Results'].value_counts()

Test Results
Abnormal        18627
Normal          18517
Inconclusive    18356
Name: count, dtype: int64

In [ ]:
df['Medication'].value_counts()

Medication
Lipitor        11140
Ibuprofen      11127
Aspirin        11094
Paracetamol    11071
Penicillin     11068
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Blood Type']=le.fit_transform(df['Blood Type'])
df['Medication']=le.fit_transform(df['Medication'])
df['Medical Condition']=le.fit_transform(df['Medical Condition'])
df['Test Results']=le.fit_transform(df['Test Results'])
df['Doctor']=le.fit_transform(df['Doctor'])
df['Hospital']=le.fit_transform(df['Hospital'])
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,1,5,2,2024-01-31,26612,29933,Blue Cross,18856.281306,328,Urgent,2024-02-02,3,2
1,LesLie TErRy,62,1,0,5,2019-08-20,33648,16012,Medicare,33643.327287,265,Emergency,2019-08-26,1,1
2,DaNnY sMitH,76,0,1,5,2022-09-22,37828,5473,Aetna,27955.096079,205,Emergency,2022-10-07,0,2
3,andrEw waTtS,28,0,6,3,2020-11-18,22511,12317,Medicare,37909.782410,450,Elective,2020-12-18,1,0
4,adrIENNE bEll,43,0,2,2,2022-09-19,21259,33598,Aetna,14238.317814,458,Urgent,2022-10-09,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,0,6,1,2020-08-16,20003,15553,Blue Cross,2650.714952,417,Elective,2020-09-15,4,0
55496,KYle pEREz,61,0,3,5,2020-01-23,37149,31722,Cigna,31457.797307,316,Elective,2020-02-01,0,2
55497,HEATher WaNG,38,0,4,4,2020-07-13,18550,37408,UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,1,0
55498,JENniFER JOneS,43,1,7,0,2019-05-25,22665,14329,Medicare,32451.092358,321,Elective,2019-05-31,1,0
55499,jAMES GARCiA,53,0,6,0,2024-04-02,10782,12207,Aetna,4010.134172,448,Urgent,2024-04-29,1,0

In [ ]:
a = df.drop(['Name', 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Admission Type', 'Discharge Date','Billing Amount','Room Number', 'Test Results'], axis=1)
a

       Age  Gender  Blood Type  Medical Condition  Medication
0       30       1           5                  2           3
1       62       1           0                  5           1
2       76       0           1                  5           0
3       28       0           6                  3           1
4       43       0           2                  2           4
...    ...     ...         ...                ...         ...
55495   42       0           6                  1           4
55496   61       0           3                  5           0
55497   38       0           4                  4           1
55498   43       1           7                  0           1
55499   53       0           6                  0           1

[55500 rows x 5 columns]

In [ ]:
x=df.drop('Test Results',axis=1)
y=df['Test Results']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=40)

In [ ]:
from sklearn.svm import SVC

training_features = ['Age', 'Gender', 'Blood Type', 'Medical Condition', 'Medication']

# Ensure x_train and x_test contain only the desired training features
x_train_filtered = x_train[training_features]
x_test_filtered = x_test[training_features]

# Re-initialize and re-train the model with the correct features
model = SVC()
model.fit(x_train_filtered, y_train)

# Now predict with the consistently filtered x_test
y_pred = model.predict(x_test_filtered)
y_pred

array([0, 0, 0, ..., 2, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
cm=confusion_matrix(y_test,y_pred)
cm
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.33585585585585587

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,y_pred)
conf=confusion_matrix(y_test,y_pred)
print(conf)

[[3872    0 1672]
 [3798    0 1692]
 [3896    0 1720]]

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,y_pred)

0.33585585585585587